name = "blackjack-api"
compatibility_date = "2024-08-06"
main = "src/server/index.ts"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[dev]
port = 8080
