[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
gas_limit = 5000000
auto_estimate_gas = true
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts",
    "forge-std/=lib/forge-std/src",
]

[rpc_endpoints]
sepolia_arbitrum = "https://sepolia-rollup.arbitrum.io/rpc"
sepolia_drtc = "https://huddle-testnet.rpc.caldera.xyz/http"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
